# Generated by Django 4.1.3 on 2022-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_customer_customer_name_customer_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="URL",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
