# Generated by Django 4.1.3 on 2022-11-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_order_url"),
    ]

    operations = [
        migrations.RenameField(model_name="order", old_name="address", new_name="etc",),
        migrations.RenameField(model_name="order", old_name="phone", new_name="wants",),
    ]
