# Generated by Django 4.1.3 on 2022-11-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_address_order_etc_rename_phone_order_wants"),
    ]

    operations = [
        migrations.RenameField(model_name="order", old_name="etc", new_name="address",),
        migrations.RenameField(model_name="order", old_name="wants", new_name="phone",),
    ]
