# Generated by Django 4.1.3 on 2022-11-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_rename_etc_order_address_rename_wants_order_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="address",),
        migrations.RemoveField(model_name="order", name="phone",),
        migrations.RemoveField(model_name="order", name="price",),
    ]
