# Generated by Django 4.1.3 on 2022-11-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_remove_order_address_remove_order_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products", name="price", field=models.CharField(max_length=60),
        ),
    ]
