# Generated by Django 4.1.3 on 2022-11-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_products_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="URL",),
        migrations.AddField(
            model_name="products",
            name="URL",
            field=models.CharField(default=111, max_length=60),
            preserve_default=False,
        ),
    ]
