# Generated by Django 4.1.3 on 2022-11-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_remove_order_url_products_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="quantity",),
    ]
